// #include <iostream>
// using namespace std;

// class CustomException : public exception {
//    public:
//     const char* what() const noexcept override { return "This is custom exception"; }
// };

// int main() {
//     try {
//         // Throwing our custom exception
//         throw CustomException();
//     } catch (CustomException e) {
//         cout << "Caught an Exception: " << e.what() << endl;
//     }

//     return 0;
// }

// Inheriting other exceptions
#include <iostream>
using namespace std;

int main() {
        return 0;
}